######################################################################
# Automatically generated by qmake (3.0) Thu Mar 12 05:51:52 2020
######################################################################

TEMPLATE = app
TARGET = Sample
INCLUDEPATH += .
QT += gui widgets

# Input
SOURCES += testmain.cpp
